helpers/UrlCleaner.php
spouts/rss/feed.php
spouts/spout.php

The purpose of this helper is to perform curl calls to get real URL.
When get, it also try to remove known trackers which are integrated as URL params or fragment.

Feat new helper urlcleaner

---

controllers/BaseController.php
controllers/Items.php
controllers/Opml.php
controllers/Rss.php
controllers/Sources.php
controllers/Tags.php
helpers/ContentLoader.php
helpers/Image.php
index.php
public/css/style.css
public/js/selfoss-events-entries.js
spouts/github/commits.php
spouts/rss/feed.php
spouts/spout.php

This pull request contains two small enhancements and a modification of how permission is denied to the application when not logged in: now the application returns a 403 error. This makes it possible to handle this particular error in js, e.g. presenting a logging prompt when an AJAX call fails because the session has expired.
It also adds a way to get a user agent for spouts.
It also fixes some stuff in getting feed icons.
(details in the commits)

Various enhancements

---

public/js/selfoss-base.js
public/js/selfoss-events-entries.js
public/js/selfoss-events-entriestoolbar.js
public/js/selfoss-events-navigation.js
public/js/selfoss-events-sources.js
public/js/selfoss-events.js

This may help in problems like #614 .

add textStatus to ajax error messages

---

controllers/Opml.php

The method signature for db interaction changed. New parameter
filter was added. This defaults it to '' during import.

Fix error during opml import

---

daos/mysql/Sources.php

This finally fixes the issue with sorting sources after error (#518).

Resetting error to SQL-NULL

---

helpers/ContentLoader.php
helpers/Image.php

Details are in the commit messages.

My queue of various fixes

---

index.php

It would be great if you could add some js/jquery code to format the design to your needs in ways that user.css could not. Adding a user.js for custom code solves this. Must also add it to .gitignore

Add custom javascript file: user.js

---

_docs/website/index.html
libs/SimplePie.php
libs/WideImage/vendor/de77/BMP.php

Various fixes for opened issues

---

controllers/Index.php
controllers/Items.php
controllers/Sources.php
index.php
public/css/style.css
public/js/selfoss-base.js
public/js/selfoss-events-entries.js
public/js/selfoss-events-entriestoolbar.js
public/js/selfoss-events-navigation.js
templates/home.phtml

- load per-source unread sources on-demand (saves initial page loading)
- unread count on top in mobile view
- periodic poll of unread stats for user interface updates.

Multiple enhancements to unread count user interface

---

daos/pgsql/Database.php

Bump version in pgsql/Database.php

---

daos/mysql/Statements.php
daos/sqlite/Statements.php

Bug was introduced in d6fd6aa68e070c2bf3173573c9b9cb13565e8e61

incorrect tag unread count, fixes #667

---

public/css/style.css

blockquote and pre's used to be stuck on one line, this fixed it

fix blockquote and pre overflow-x resetting

---

README.md
_docs/website/index.html

This patch fix the ArtCore URL to http://www.artcoreillustrations.com/

Fix ArtCore URL

---

public/css/style.css

If the user uses dark theme, the text can be illegible. When changing a background color, the font color should be changed too.

Add base font color

---

public/js/selfoss-shortcuts.js

Can't help to think there is probably a good reason for the lack of such a shortcut.
I added it anyway, can be useful...
Any thoughts on this ?

Add keyboard shortcut to refresh sources (Shift+r)

---

templates/home.phtml

Do not inform pages about the URL of the selfoss installation.

added no-referrer meta tag

---

index.php
public/js/selfoss-events-navigation.js

Fix API collision

---

daos/mysql/Database.php

Update Datebase bug on db change to version 9

---

templates/home.phtml
templates/login.phtml

This patch  fix the  "Selfoss" web application name.

Use "selfoss" instead "Selfoss" as web application name

---

public/lang/fr.ini

Add french translations for `filter` and `searchremove`.

[FR] Missing translations

---

spouts/twitter/listtimeline.php
spouts/twitter/usertimeline.php

spouts\twitter: Add support for private feeds

---

spouts/reddit/reddit2.php

Fix reddit spout

---

controllers/Index.php
controllers/Sources.php
daos/Sources.php
helpers/ContentLoader.php
helpers/FileNotFoundException.php
index.php
public/css/style.css
public/js/selfoss-events-entries.js
public/lang/cs.ini
public/lang/en.ini

Allow updating a single source

---

spouts/rss/golem.php
spouts/twitter/usertimeline.php
templates/home.phtml
templates/item.phtml

Thanks to this article. 
https://dev.to/phishing

Prevents window.opener vulnerability. 

---

daos/mysql/Items.php
daos/mysql/Statements.php
daos/mysql/Tags.php
libs/f3/db/sql.php

See https://github.com/SSilence/selfoss/issues/811 and https://github.com/SSilence/selfoss/issues/534#issuecomment-172329123

Fix #811 - fetch and show emoji icons

---

controllers/Index.php
daos/mysql/Items.php
daos/mysql/Statements.php
public/js/selfoss-base.js
public/js/selfoss-events-entries.js
public/js/selfoss-events-navigation.js
public/js/selfoss-events-search.js
public/js/selfoss-events.js
templates/home.phtml
templates/item.phtml

Revert "Make selfoss navigable"

---

spouts/twitter/usertimeline.php

A htmLawed interference, closes #825

Fix twitter links when tweet contains <

---

controllers/Sources.php
helpers/ContentLoader.php
public/js/selfoss-events-sources.js
public/lang/cs.ini
public/lang/en.ini
spouts/github/commits.php
spouts/rss/feed.php
spouts/spout.php
spouts/twitter/hometimeline.php
spouts/twitter/listtimeline.php
spouts/twitter/usertimeline.php
templates/source.phtml

This is my attempt at automatic fetching of title.
The title is fetched when saving the spout without title filled in. Unlike #838, this also has complete spout coverage.
cc  @niol

Automatically fetch feed title

---

spouts/reddit/reddit2.php

Improve error reporting for reddit spout

---

.travis.yml
README.md
utils/bintray.json
utils/bintray.sh
utils/package.sh

Add script for deploying commit builds to Bintray

---

controllers/Index.php
controllers/Opml.php
controllers/Sources.php
controllers/Tags.php
daos/Items.php
daos/Sources.php
daos/Tags.php
daos/mysql/Database.php
daos/mysql/Items.php
daos/mysql/Statements.php
daos/pgsql/Statements.php
daos/sqlite/Statements.php
helpers/Anonymizer.php
helpers/ContentLoader.php
helpers/View.php
helpers/WebClient.php
phpstan.neon
spouts/github/commits.php
spouts/reddit/reddit2.php
spouts/rss/feed.php
spouts/twitter/usertimeline.php

See [phpstan](https://github.com/SSilence/selfoss/tree/phpstan) branch.

Fix problems reported by PHPStan level 0

---

helpers/Image.php
spouts/rss/feed.php

This PR brings favicons to these two feeds:
* https://feeds.feedblitz.com/recordedfuture
* https://www.contextis.com/resources/blog/blog.xml

Improve favicon fetching

---

helpers/WebClient.php

Introduced in e1316a443dbdc4de966c836c2ff5b9892489b879

Fix accessing undefined variable in WebClient

---

controllers/Opml.php
daos/Sources.php
helpers/Color.php
helpers/ContentLoader.php
helpers/View.php
spouts/rss/images.php
spouts/youtube/youtube.php

This prevents checks form failing for future pull requests.

php syntax fixes (after php-cs-fixer update to 2.4.0)

---

helpers/ContentLoader.php
public/css/style.css

Various overflow fixes

---

public/js/selfoss-ui.js

Fixes refreshEntryStatuses' name #1030

---

composer.json
composer.lock

composer: fix warning

---

assets/hashpassword.html
assets/js/selfoss-ui.js

Fixed the typo in the id. Previously it wash incorrectly: 'hashpashwordbody'. Fixed it.

Fixed the typo in the id of 'hashpassword.html' and 'selfoss-ui.js'

---

README.md

Fix some grammar issues and clean up style.

readme: touch up

---

.gitignore
.php_cs
.travis.yml
composer.lock
package.json
src/common.php
src/controllers/Index.php
src/controllers/Sources/Update.php
src/controllers/Sources/Write.php
src/helpers/Authentication.php
src/helpers/ContentLoader.php
src/helpers/View.php
src/spouts/reddit/reddit2.php
src/templates/item.phtml
src/templates/source.phtml
tests/integration/helpers/data_server.py
tests/integration/helpers/feeds/fibonacci.py
tests/integration/helpers/integration.py
tests/integration/helpers/selfoss_api.py
tests/integration/helpers/selfoss_server.py
tests/integration/php.ini
tests/integration/run.py

To be able to see if PHP 8 works.
Currently fails due to `requests` library seemingly not to being able to extract cookies.

Create basic integration testing

---

.github/workflows/main.yaml
.travis.yml
flake.lock
utils/create-zipball.py
utils/package.sh

Travis requires people to jump through support hoops these days. Thanks for all the years of service, though.

ci: Switch to GitHub actions

---

assets/js/index.js
assets/js/selfoss-base.js
assets/js/selfoss-ui.js
assets/js/shortcuts.js
assets/js/templates/App.jsx
assets/js/templates/EntriesPage.jsx
assets/js/templates/Item.jsx
assets/js/templates/NavFilters.jsx
assets/js/templates/NavSearch.jsx
assets/js/templates/NavSources.jsx
assets/js/templates/NavTags.jsx
assets/js/templates/NavToolBar.jsx
assets/js/templates/Navigation.jsx
assets/package-lock.json
assets/package.json

Fixes: https://github.com/fossar/selfoss/issues/1029

Upgrade jQuery

---

NEWS.md
README.md
docs/content/_index.md
utils/create-zipball.py
utils/generate-config-example.php

Update docs and changelog.
Also remove the `globals` section since the new configuration system ignores them.
Follow up on #1261

Rename defaults.ini to config-example.ini

---

assets/js/shortcuts.js
assets/js/templates/EntriesPage.jsx
assets/js/templates/Item.jsx

This should fix various bugs when navigating by keyboard.
Fixes: https://github.com/fossar/selfoss/issues/1288

Reduce use of DOM for actions

---

src/common.php
src/daos/CommonSqlDatabase.php
src/daos/DatabaseInterface.php
src/daos/mysql/Database.php
src/daos/mysql/Items.php
src/daos/pgsql/Database.php
src/daos/sqlite/Database.php
src/helpers/DatabaseConnection.php

Do not use F3 for database handling

---

NEWS.md
assets/js/selfoss-shares.js
assets/js/shortcuts.js
assets/js/templates/Item.jsx
src/spouts/twitter/usertimeline.php

Improves privacy and performance.

Disable more instances of sending referrer header

---

assets/js/helpers/authorizations.js
assets/js/selfoss-base.js
assets/js/selfoss-db.js
assets/js/templates/App.jsx
assets/js/templates/EntriesPage.jsx
assets/js/templates/Item.jsx
assets/js/templates/NavSources.jsx
assets/js/templates/NavToolBar.jsx
assets/js/templates/Navigation.jsx
assets/styles/main.scss

And also fix mark/starr event handler when authorization is disabled.

client: Centralize permission handling

---

NEWS.md
src/spouts/Item.php
src/spouts/reddit/reddit2.php
src/spouts/rss/fulltextrss.php

- spouts: Support lazy item contents
- spouts: Support lazy item icons

spouts: Support lazy item contents

---

client/.sassrc
client/js/templates/Source.jsx
client/package-lock.json
client/package.json

- @fortawesome/free-brands-svg-icons: 6.5.2 → 6.7.1
- @fortawesome/free-regular-svg-icons: 6.5.2 → 6.7.1
- @fortawesome/free-solid-svg-icons: 6.5.2 → 6.7.1
- parcel: 2.12.0 → 2.13.2
https://github.com/parcel-bundler/parcel/releases/tag/v2.13.0
https://github.com/parcel-bundler/parcel/releases/tag/v2.13.1
https://github.com/parcel-bundler/parcel/releases/tag/v2.13.2
- @parcel/packager-raw-url: 2.12.0 → 2.13.2
- @parcel/service-worker: 2.12.0 → 2.13.2
- @parcel/transformer-image: 2.12.0 → 2.13.2
- @parcel/transformer-sass: 2.12.0 → 2.13.2
- @parcel/transformer-webmanifest: 2.12.0 → 2.13.2
- @szhsin/react-menu: 4.1.0 → 4.2.3
https://github.com/szhsin/react-menu/releases/tag/v4.2.0
https://github.com/szhsin/react-menu/releases/tag/v4.2.1 …

client: Update dependencies

---

NEWS.md
client/js/locales.js
docs/content/docs/administration/options.md

Fully translated in 4559fd0dde7d26f36973371392d05079bbd069ce by @TamilNeram. Many thanks.

Add Tamil translation

---

docs/content/docs/administration/options.md
docs/content/docs/customization/spouts/index.md
docs/content/docs/project/release-checklist.md
docs/content/docs/usage/filters.md
docs/sass/style.scss

We had several people confused by the docs.
Fixes: https://github.com/fossar/selfoss/issues/1519
https://github.com/fossar/selfoss/issues/1480#issuecomment-2277395611

docs: Annotate features requiring 2.20

---

docs/templates/index.html

Noticed this link was outdated when clicking around.

Fix broken link to F-Droid
