fossar/selfoss

helpers/Authentication.php
Under certain conditions the server may set `$_SERVER['HTTPS']` but it will be empty ([this is expected](http://php.net/manual/en/reserved.variables.server.php)) and it would be `"off"` only in some cases.
Because of this, the cookie isn't set and the user experiences a login loop with no error whatsoever, as previously commented on issue #581 and [on the selfoss support forum](http://selfoss.aditu.de/forum/index.php?id=530).
This pull request fixes the issue checking if `$_SERVER['HTTPS']` is empty.
=> Fix login auth loop due to cookie not being set over HTTP

helpers/ContentLoader.php, helpers/Image.php
Now, thumbnails are always converted to jpeg instead of png. This drastically decreases data usage on spouts like Twitter and is especially useful when you're on a mobile data connection.
Favicons are still converted to png, but a slight compression was added for further data savings.
=> convert thumbnails to jpg

helpers/ContentLoader.php
Allowing the target attribute within sanitizeField enables hyperlinks in titles to be opened in a new browser tab. This is especially useful for links within tweets.
=> allow target attribute

.gitignore, _docs/website/index.html, common.php, defaults.ini
I am preparing to run selfoss in a PaaS like Heroku. For that it must be possible to configure the app - at least partially - through ENV variables.
Even if I would bundle it up using Docker with configuration files, one would have to build a new Docker image upon mine to have his/her own config. (E.g. to change the salt, the username/password, the db credentials and so on)
That's why I implemented an easy way to set selfoss config variables though ENV variables. To prevent accidental conflicts the variables, by default, must be prefixed with a configurable prefix. I have pre-defined that prefix in defaults.ini to be "SELFOSS_". (The prefix check is case insensitive and the variable will be converted to lower case before adding it to f3.)
It would be nice to see this change integrated …
=> Config from env

.htaccess
Although magic_quotes_gpc was removed from recent PHP versions, f3 would not start without this property set. This patch fixes setups where this property is not set.
And because it is deprecated or removed, it does not matter if we overwrite it accidentally.
=> F3 would not launch when "magic_quotes_gpc" is not set.

helpers/ContentLoader.php, helpers/Image.php, helpers/WebClient.php, libs/f3/web.php, spouts/github/commits.php, spouts/rss/feed.php, spouts/spout.php
This helper can replace all custom curl calls in spouts. It uses f3 internals, so it can use sockets, curl or file_get_contents(), and it logs and throws errors as exceptions.
=> New webclient helper

public/js/selfoss-events-entriestoolbar.js
As of PHP 5.6, `$HTTP_RAW_POST_DATA` is deprecated. Sending a POST request without Content-Type populates `$HTTP_RAW_POST_DATA`, which triggers an `E_DEPRECATED`.
It makes the Star / Unstar button fail:
Request:
```
POST /selfoss/starr/26110 HTTP/1.1
Host: ...
Connection: keep-alive
Content-Length: 0
Accept: */*
Origin: ...
X-Requested-With: XMLHttpRequest
User-Agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2398.0 Safari/537.36
DNT: 1
Referer: ...
Accept-Encoding: gzip, deflate
Accept-Language: fr,en-US;q=0.8,en;q=0.6
Cookie: PHPSESSID=...
```
Response headers:
```
HTTP/1.1 500 Internal Server Error
Server: nginx/1.6.0
Date: Tue, 19 May 2015 07:40:49 GMT
Content-Type: text/html; charset=UTF-8
Transfer-Encoding: chunked
Connection: …
```
=> "$HTTP_RAW_POST_DATA is deprecated" error

defaults.ini, public/js/selfoss-base.js, templates/home.phtml, templates/login.phtml, templates/opml.phtml
When running multiple installations of selfoss all installations show the same HTML title. I've added a configuration that defaults to 'selfoss' but can be overriden by the user so one is able to differentiate between different installations depending on the title.
=> Allow configuration of html <title>

public/js/selfoss-events-sources.js
Same as #664, but when deleting a source.
Fixes the second part of #643.
=> "$HTTP_RAW_POST_DATA is deprecated" error when deleting a source

public/css/style.css
According to gained knowledge in #671 this makes wordpress smilies integrate into continuous text more smoothly
=> inline and resize emojis to fit into text flow

daos/mysql/Sources.php, helpers/ContentLoader.php
Instead of assuming that the date of the last entry is the same as the date of the last update that added new items (what could be horribly wrong...), we can use the date specified by the newest item itself.
As suggested by @niol (https://github.com/SSilence/selfoss/pull/679#issuecomment-116114194); see https://github.com/SSilence/selfoss/pull/679#discussion_r33422101
=> Use the date specified by the items as the date of the last entry

daos/mysql/Database.php
Mysql Database didn't have default value for table **Item** field **updatetime** and this is required for the correct functionality of the application.
=> Set Default value for updatetime on MYSQL

_docs/website/index.html, defaults.ini, public/js/selfoss-events-entries.js, templates/home.phtml
Added a new feature auto_collapse.
It can be used by setting `auto_collapse=1` in the config.ini file. By default the value is set to 0 and the feature is deactivated.
When activated the open items will collapse automatically when another item is opened, thereby making the interface even more clutter free and easy to browse.
=> Auto collapse

daos/mysql/Sources.php
After upgrading from 2.12 to 2.14, Settings screen cannot be opened, showing a red alert with message "Load list error: error Internal Server Error". If tables are using a custom prefix, "AS items" are needed on SQL statements.
=> Settings cannot be opened

daos/mysql/Items.php
When you want to scale an application, it's sometimes better to not use JOIN statements.
Many fast SQL queries are often better than a slow one.
That's exactly the case here where, on a small server, JOIN operations will systematically use tmp tables. In that case, it's better to do the join in PHP.
More, there are absolutely no need for a JOIN just to check whether we have more items
=> Remove joins from daos/mysql/Items.php

daos/mysql/Items.php
Having a quite huge instance (>250k items, >500 sources), cleaning unused icons run for ages.
Example today:
10-27-15 16:20:01 ---
[...]
10-27-15 16:27:53 Debug cleanup orphaned and old items
10-27-15 16:27:56 Debug cleanup orphaned and old items finished
[...]
10-27-15 16:27:56 Debug delete orphaned thumbnails
10-27-15 16:28:00 Debug delete orphaned thumbnails finished
[...]
10-27-15 16:28:00 Debug delete orphaned icons
10-27-15 16:47:30 Debug delete orphaned icons finished
[...]
10-27-15 16:47:30 Debug optimize database
10-27-15 16:49:43 Debug optimize database finished
As you can see, deleting orphaned icons runs for 20 minutes. This is due to the SQL request which performs a count, means that it'll scan the whole item's table.
If you just want to know wether a given icon is still used …
=> Optimize SQL request to look for icon usage

controllers/Index.php, controllers/Items.php, daos/Items.php, daos/Sources.php, daos/Tags.php, defaults.ini, helpers/Authentication.php
Hello,
I had these patches in my version of selfoss since quite a while, and I wanted to suggest it to you.
It add the ability 
1/ to have private tags (with a @ in the tag name). Items (and sources) with such tags won't be visible in the feed if the user is not logged in.
2/ to have "not important" tags (with a # in the tag name), whose items won't be visible in the "all tags" feed, but only when you click directly on the tag or source.
Currently the # and @ symbols are hardcoded, but I can update the code to allow the configuration in defaults.ini (or even disabling it with an empty value).
=> Add support for private (@) and hidden (#) tags

spouts/rss/enclosures.php
According to the SimplePie docs, the `get_enclosures()` method...
> Supports the \<enclosure> RSS tag, as well as Media RSS and iTunes RSS.
Example: https://erzaehlmirnix.wordpress.com/feed/
=> Add spout "RSS Feed (with enclosures)" to support feed enclosures

controllers/Sources.php, public/css/style.css, public/js/selfoss-events-entriestoolbar.js, public/js/selfoss-events-navigation.js, public/js/selfoss-shortcuts.js, public/lang/cs.ini, public/lang/en.ini, spouts/rss/feed.php, spouts/rss/fulltextrss.php, spouts/rss/instapaper.php, spouts/rss/readability.php, templates/home.phtml, templates/item.phtml, templates/login.phtml, templates/opml.phtml, templates/source-nav.phtml, templates/source.phtml, templates/source_params.phtml, templates/tag.phtml
I added some labels and converted most of the action divs/spans into real buttons or tabindexed pseudo-links. Whole interface should be now controllable by keyboard but that can be quite tedious. Later I will try to add more [role attributes](https://www.w3.org/TR/wai-aria/roles) which should make it much more convenient.
I also don’t know how good is the screen readers’ support for dynamically added elements (the form to add a new source). Maybe I will need to use [ARIA live regions](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Live_Regions).
Search form is hidden beneath the sidebar but it is probably accessible for screen readers, not sure if it is okay. I added [search role](https://www.w3.org/TR/wai-aria/roles#search), is it enough or is a heading needed?
The …
=> [WIP] Improve accessibility

.htaccess
This folder is used by letsencrypt to prove ownership of domain.
Adding the exception to the ``.htaccess`` file allows the letsencrypt server to fetch a generated filed in this folder.
For more information, see https://letsencrypt.org/
=> Added Rewrite Rule for ACME well known location.

libs/floIcon.php
Constructors with the same name as the class have been deprecated in PHP 7. This caused an error on a fresh installation of selfoss in an environment with PHP 7.
=> Rename floIcon constructors

public/js/selfoss-events-search.js
When scrolling enough to trigger the auto-stream and then going back to top to perform a search, the search keeps the previous offset instead of starting with an offset of zero.
=> Fixed the search offset

public/js/selfoss-base.js
Since f02c300, when selecting a source for the first time, the filter is applied as expected on the entries list but the highlight on the source is added and instantly removed.
After the first source selection, clicking on another source highlights the source as expected.
It affects #747 since it uses the active source to count the number of unread entries.
=> Fixed the "active" flag in the sources list

public/css/style.css, public/js/selfoss-base.js, public/js/selfoss-events-entries.js, public/js/selfoss-events-navigation.js, public/js/selfoss-events.js, templates/home.phtml
Unread entries might appear far down in the list of entries for many reasons. For example, when marking a source as read, the recent entries list will be a mix of read / unread entries.
When marking everything as read we might have missed a few unread entries because they were too far down in the list.
This PR adds an indicator displaying the number of unread entries below the fold:
It only appears on desktop browsers (width > 1024px), and requires the `floating_unread_count_enabled=true` config parameter to be shown (disabled by default).
It might display `?` when the number of unread entries is unknown, for example when using the search feature.
=> Added an indicator of "below the fold" unread entries

controllers/Index.php, defaults.ini, helpers/Authentication.php
This patch changes the password hashing system to use `password_hash` and `password_verify` rather than sha512. This system uses a more expensive hashing function to make brute-forcing infeasible. It also generates its own salt securely, so you don't need to worry about that.
Unfortunately, this does bump the PHP requirement to 5.5. Since 5.3 is not officially supported anymore, this should not be too much of a problem.
=> Use a more secure password hash

spouts/rss/golem.php
This patch tweaks the Golem.de spouts a little bit. It remove adds inside the content and replace a gallery with a single image and a link to all.
=> Clean the Golem.de content a little bit

public/css/style.css, public/js/selfoss-events-navigation.js, templates/home.phtml
This patch allow to collapse/expand the filter list like the tags and the sources.
=> Allow to collapse/expand filter list

templates/home.phtml
The img src to remove.png and search.png (added with 462e91ccfb522b37a20a848d57d77d15364709af) causes broken links to these images.
default.log:
06-25-16 9:26:23 Error HTTP 404 (GET /public/images/remove.png)
06-25-16 9:26:23 Error HTTP 404 (GET /public/images/search.png)
=> Fix img src path to search.png and remove.png

helpers/Authentication.php, helpers/View.php
selfoss should use the URL the application is actually accessed through, instead of the script location (which may differ).
=> Handle rewritten URLs correctly

controllers/Index.php, controllers/Items.php, daos/Items.php, daos/Sources.php, daos/Tags.php
Cherry-picked https://github.com/wazari972/selfoss/commit/3853d6423c3925978119ed0be0171da1611ca5a4, should fix the error reported in #740 (not the issue itself though). It will also make hidden tags actually work as promised in #714.
Problems not fixed in this pull request:
* _Unread_ filter count is subtracted multiple times when a feed has multiple hidden tags (it can even show negative count).
* _Unread_ filter count is not AJAX-updated when you tag/untag a source with a hidden tag.
* Number of unread items below the fold (#747) doesn’t subtract the hidden items.
* Private tags are still displayed in sidebar, although they correctly don’t show any content.
* There is not documentation.
=> Fix read count of secondary tags

_docs/website/index.html, common.php, defaults.ini, helpers/ViewHelper.php, libs/WillWashburn/Phpamo/Encoder/EncoderInterface.php, libs/WillWashburn/Phpamo/Encoder/HexEncoder.php, libs/WillWashburn/Phpamo/Encoder/QueryStringEncoder.php, libs/WillWashburn/Phpamo/Formatter/FormatterInterface.php, libs/WillWashburn/Phpamo/Formatter/HexFormatter.php, libs/WillWashburn/Phpamo/Formatter/QueryStringFormatter.php, libs/WillWashburn/Phpamo/Phpamo.php, templates/item.phtml
I used selfoss every day with a Let's Encrypt certificate but the connection is not fully encrypted when some feeds have images that does not come from https. To address this situation I used https://github.com/atmos/camo (an http proxy to serve images through SSL). It's optional so if the configuration for host and key are empty, nothing is done.
=> Optionaly proxify images src with atmos/camo

public/css/style.css, public/js/selfoss-events-entries.js, public/js/selfoss-events-entriestoolbar.js, public/js/selfoss-events-navigation.js, public/js/selfoss-shortcuts.js, templates/item.phtml, templates/source-nav.phtml
Clicking the item’s source (previously opened item’s URL) will open the source’s list of items, similar to how the tags open tag listing. The item’s URL can be now opened by clicking the date, consistent with other applications like Twitter.
=> Link entry source to source listing

common.php
Update of f3 framework to version 3.5.0 contained following change
```
Change in behavior: ERROR.trace is a multiline string now
```
which broke our trace handling in `ONERROR`.
Closes #800
=> Fix error handler causing an error

controllers/Sources.php
It makes no sense that unauthenticated user can view pretty much anything but cannot view a list of sources to switch to a different one.
=> Allow to change source in public mode

spouts/rss/heise.php
See http://www.heise.de/newsticker/meldung/Verschluesselung-heise-online-und-Heise-Onlinedienste-per-HTTPS-erreichbar-3331421.html
=> Heise spout: Use HTTPS to retrieve feeds

spouts/rss/heise.php
Heise recently enabled https access for all services. So use it.
=> Use https for Heise RSS Feeds

_docs/website/index.html, defaults.ini, public/js/selfoss-events-entries.js, templates/home.phtml
The scroll to the article header can be really annoying when reading articles from bottom to top.
The boolean option "scroll_to_article_header" allows to disable the scroll. It is still enabled by default to keep the current behavior.
=> Added the scroll_to_article_header option

public/js/selfoss-events-navigation.js
PR #794 allows to specify a callback to be executed after expanding the list of sources. The argument was called even when no callback was passed, resulting in an error.
This commit adds a check whether the callback is specified.
=> js: Fix expanding list of sources

daos/mysql/Database.php
PR #813 updated the MySQL code to use proper unicode charset, this commit adds an upgrade script for seamless transition of existing installations.
=> Add upgrade script for conversion to utf8mb4

helpers/ViewHelper.php
Loading HTML in DomDocument create encoding issues.
Additionally, regex are faster than loading a document tree.
I often found this issue with fulltextrss spout and French feeds.
There might be another problem with encoding with this spout.
Indeed, I get similar problems on selfoss android app even if I apply this fix.
=> Fix encoding problems caused by camo

.htaccess, _docs/website/index.html, controllers/Items.php, daos/pgsql/Database.php, helpers/Authentication.php, public/lang/fr.ini
Various fixes detailed in the individual patches.
=> Various fixes

controllers/Index.php, daos/mysql/Items.php, daos/mysql/Statements.php, public/js/selfoss-base.js, public/js/selfoss-events-entries.js, public/js/selfoss-events-entriestoolbar.js, public/js/selfoss-events-navigation.js, public/js/selfoss-events-search.js, public/js/selfoss-events.js, templates/home.phtml, templates/item.phtml
These patches make selfoss navigable using the url hash. This makes the url reflect whats displayed in selfoss. This also makes it possible to reload the item that was open before a browser crash or when the tab containing selfoss was offloaded from memory on a mobile browser.
=> Make selfoss navigable

public/js/selfoss-events-entries.js
Fixes another instance of #565, this time when refreshing single source.
=> Prevent “$HTTP_RAW_POST_DATA is deprecated” error

controllers/Sources.php
Fixes #734 for `/source` and `/source/@id` endpoints. Requires f3 3.6.0 to work (use #845).
=> Add JSON support for Sources::write

controllers/Rss.php
Apparently, this broke after FeedWriter update.
=> Fix feed not being printed

controllers/Rss.php
To make it pass validation, the following was needed:
1. Adding channel description
2. Removing HTML tags from title
3. Setting GUID
4. Correctly setting `lastPubDate`
Additionally, `self` URL was added as suggested by the [validator].
No problems with encoding detected after adding [feed suggested] in original issue.
Closes: #492
[validator]: https://validator.w3.org/feed/
[feed suggested]: https://alphaomegaalpha.wordpress.com/feed/
=> Make generated RSS valid

daos/mysql/Database.php
Reverting SSilence/selfoss#697 since we already have triggers and this breaks compatibility with MySQL 5.5.
=> Revert "Set Default value for updatetime on MYSQL"

.travis.yml
We are linting the code on all supported versions of PHP.
Note that we remove TwitterOAuth library when running PHP older than 5.6 because TwitterOAuth declares 5.6 as minimal version. Except for one small detail, I have filed a pull request for, it still works, though.
=> Add syntax linting using Travis

controllers/Opml.php, controllers/Sources.php, daos/mysql/Sources.php
The key first appeared in the initial commit (045dd9bb06d0664c51bba4d6da7868d93ab95ffb) but it does not look like it was used anywhere apart from the OPML controller. To make future changes easier, I am removing it.
Does anyone have any idea what is it for?
=> Remove spout_obj key

controllers/Index.php, controllers/Items.php, daos/mysql/Database.php, daos/mysql/Items.php, daos/pgsql/Database.php, helpers/ViewHelper.php, index.php, public/css/style.css, public/js/selfoss-base.js, public/js/selfoss-db.js, public/js/selfoss-events-entries.js, public/js/selfoss-events-entriestoolbar.js, public/js/selfoss-events-navigation.js, public/js/selfoss-events.js, public/js/selfoss-ui.js, templates/home.phtml, templates/item.phtml
This PR includes #834 .
Those changes add a new /items/sync API endpoint that sends database changes from a given datetime. This ensures only data absent from the client side is sent. This PR includes some client side changes to take advantage of this, including some functional enhancements such as cross-device updating of item statuses.
=> Sync client from server using last update timestamp

.gitignore, .php_cs, .travis.yml
* https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/2505
* https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/2459
--------------------
Travis will check for coding style violations.
Symfony Coding Style mostly works for selfoss. It is essentially PSR-2 sprinkled with some more rules for cases when PSR-2 is silent. When the code base was not consistent, I choose the most common format.
These are the deviations from Symfony CS:
* Opening braces after functions, methods, classes, interfaces, traits, etc. go on the same line. (Unlike PSR-2)
* Lambdas do not have a space after function keyword. (Unlike PSR-2)
* Concatenation operator `.` requires spaces from both sides. The codebase was actually fairly tied on this issue: 170 vs 167
lines had to be changed. The spaced variant was, however, …
=> Add coding style checker

.gitignore, README.md, _docs/website/index.html, helpers/View.php
This change makes the js and css generated to a file containing the
max mtime of source material in its name. Therefore, each time the
source js or css files are changed, a new file with a new name gets
generated and referenced in the app. From the client browser's view,
this is a new ressource that needs to get fetched regardless of the
cache status of older css or js.
The trade-off is that each request implies stat'ing each source
material file. There is no notiecable time penalty in loading time.
=> make it unlikely that the client browser gets outdated js or css

spouts/youtube/youtube.php
This pull request fixes the youtube spout to make it work with the following urls :
- `https://www.youtube.com/channel/<channel-id>` where `<channel-id>` contains an hyphen;
- `https://www.youtube.com/user/<username>`.
=> Fix youtube spout

daos/mysql/Database.php, daos/mysql/Items.php, daos/pgsql/Database.php, daos/sqlite/Database.php, helpers/ContentLoader.php
=> Keep track when was an item last seen in a feed

run.php
Pull request #907 switched to using query string as a cache busting strategy but the runner for the PHP built-in server did not anticipate any text after file name extension.
See also: https://github.com/SSilence/selfoss/issues/910
=> Fix asset routing for PHP built-in server

spouts/rss/feed.php
When RSS feed item link redirects to a different site (e.g. Feedburner) and there are no icon link elements, favicon.ico in the root of the site will be checked. Unfortunately, the site root is determined from the original item link before redirection, therefore incorrect icon might be used. Until we can determine the correct site root easily, possibly once we switch to Guzzle, the original behaviour is preferred.
Additionally, the commit caused that the links in link aggregators like Haskell News used the favicon of the first link.
This reverts commit cac783d75cd6d81ac545879d5b45f39432236d20.
=> Revert "Prefer item link for obtaining favicon"

helpers/Image.php
When loading an image, the data were written to a file to determine the file type. This file was previously cleaned but the clean-up was accidentally dropped in d1307573d3d75a7a8078c8e2942c44ba6aa63036.
PHP 5.4 introduced `getimagesizefromstring` function, which allows to use data already in memory, removing the need for writing to a temporary file and thus a clean-up.
=> Do not use cache unnecessarily

gruntfile.js
In 4e4094cc0d492fe1022a25619d69cba26b8c2f95, client side `package.json` was erroneously added to the blacklist of files to be included in the built package.
=> Fix client side manifest not included into built package

controllers/Index.php, controllers/Items.php, controllers/Opml.php, controllers/Tags.php, daos/mysql/Items.php, helpers/ViewHelper.php, index.php, public/css/style.css, public/js/selfoss-base.js, public/js/selfoss-db.js, public/js/selfoss-events-entries.js, public/js/selfoss-events-navigation.js, public/js/selfoss-events-search.js, public/js/selfoss-events.js, public/js/selfoss-ui.js, public/package.json, templates/hashpassword.phtml, templates/home.phtml, templates/item.phtml
Some minor enhancements and refactoring, use API for login and update item datetimes client-side.
=> Improve js client

spouts/twitter/usertimeline.php
In 481ecf3d507870d9194587987b320b46f90791f9, we have switched to using full text body of tweets. Unlike the previously used `text` property, the `full_text` string is already HTML-escaped.
The spout no longer needs to escape the text.
=> Do not double-escape tweet bodies

spouts/github/commits.php
3c9da8de68763c86c700496cda0c38b978d832ef broke obtaining the favicon.
Since the icon is always the same, this patch fixes it by hardcoding the URL, saving a roundtrip to GitHub servers.
=> Fix favicon for GitHub spout

public/package.json
Since Debian-provided version of NPM does not support scoped packages, we have to install FancyBox from Git. I also changed the dependency name in the `package.json` to just `fancybox` in order
not to trigger the outdated NPM. Apparently, this will make NPM think the package is extraneous due to a mismatch between the package name and the name in the `package.json`.
=> Fix fancybox being considered extraneous package

.php_cs, composer.json
When we introduced the use of Composer classmaps for autoloading in df6f5d033ff73c4a29e9118abcb0ae7968710009, we lost the ability to define custom spouts without dumping the autoloader. PSR-4 would fix this issue but at the time I came to conclusion we would have to change selfoss file structure to support it.
Since that assumption seems to be false, we are switching to PSR-4, thus having the cake and eating it too. The only caveat is the need for more strict file naming conventions.
Closes: #958
If you use any custom classes like spouts, make sure they follow [PSR-4], namely the namespace should match the file path (even in letter case).
For example, if you have custom spout class named `PrivateSpout` in `spouts\private` namespace, it will have to be located in …
=> Use PSR-4 for autoloading

public/js/selfoss-db.js, public/js/selfoss-events.js
Pull Request #931 moved the authentication client side, which worsened the issue #919 by displaying error instead of the login form on opening selfoss when user did not log out and their session expired on the server.
This patch redirects user to login form whenever client side session is registered and 403 Forbidden error is received.
This is a temporary fix before offline support is merged.
=> client: Log out user instead of showing 403 Forbidden error

public/js/selfoss-events.js
In 8946e49e75e8b82815e341f683badf2a40e97e79, we upgraded the scrollbar plug-in. Due to [changes] in version 3.1.0 of the plugin, the height of a hidden container is set to zero. This caused the navigation to be invisible in mobile layout.
With this patch, the scrollbar library will only be initialized when using desktop layout.
Closes: #953
[changes]: https://github.com/malihu/malihu-custom-scrollbar-plugin/commit/12513564a32dbb7638dbf70b3d9d8b3f1b6655e8#diff-379285ae10c1a5aad9c2ba1ccd07dd96L517
=> Fix navigation on mobile

daos/mysql/Database.php, daos/pgsql/Database.php, daos/sqlite/Database.php
In 14442c03b882a8f4e2255c5b654459a7bd8c5f78, `updatetime` field was introduced to the `items` table. Unfortunately, unlike the initialization, the migration did not flag the field `NOT NULL`. Additionally, the `lastseen` column in MySQL database was added as `NULL`able in 83794f415e4ba8b8339b1236155d52769e799dc6. These inconsistencies can lead to incorrect assumptions and cause bugs like #954.
This PR fills the `NULL` fields during SQLite migration, fixing #954, and adds the `NOT NULL` constraint for `updatetime` and `lastseen` fields, making them consistent accross databases and migration paths.
=> Fix database migration and make them more consistent

templates/source.phtml
The favicons in the source list contained the title of the feed in their alt attribute. This was redundant since the title is already shown next to the item, resulting in the title being read multiple times by accessibility technologies. It was also displayed over the title when the favicon file was missing.
Closes: #975
=> Drop alt attribute of source favicons

package.json
On Heroku and other services, client side resources are not installed since the client package.json is in a subdirectory. We need to install them manually.
This patch adds the client installation script into postinstall hook.
Please note that you still need to enable node.js buildpack (or carry out an equivalent procedure for your PaaS) for the hook to be run.
=> Fix compatibility with PaaSs

public/package.json
=> prevent privacy breach (loading jquery.mousewheel from Cloudflare CDN)

public/css/style.css
Top margin pushed entry icons out of their parent links, resulting in difficulties when clicking the icon on mobile devices.
This patch removes the margin and adds a padding for even better clickability.
=> Improve entry icon style

composer.json, composer.lock
To support recently released PHP 7.2, we need to update dependencies. Since there is [no stable release](https://github.com/bcosca/fatfree-core/issues/226), we use fatfree from git. We also use our own htmlawed composer package because `htmlawed/htmalawed` is seemingly abandoned.
Closes: #983
=> composer: bump dependencies

public/lang/fr.ini
'Marquer tout comme lu' means 'Mark all read', which is wrong: the button
only marks visible read.
=> fix fr lang_markread

helpers/ContentLoader.php
=> contentloader: log warning when icon/thumbnail directories are not writeable

NEWS.md, _docs/website/index.html, common.php, defaults.ini
This PR adds a new configuration option `logger_destination` allowing to choose between Monolog’s [`ErrorLogHandler`](https://github.com/Seldaek/monolog/blob/master/src/Monolog/Handler/ErrorLogHandler.php) and [`StreamHandler`](https://github.com/Seldaek/monolog/blob/master/src/Monolog/Handler/StreamHandler.php).
=> logging: Allow logging to web server error_log

docs/api-description.json, gruntfile.js
This patch adds the description of the RESTful API in OpenAPI 3.0 format. Previously, the API was manually documented on the wiki without any guarantee that the description matches reality. Formal description will allow us to check for compliance automatically, as well as use other cool tools like Swagger UI.
For now, you can view the API on https://app.swaggerhub.com/apis/jtojnar/selfoss/2.18-SNAPSHOT
Closes: #993
cc @niol
=> Add machine-readable API description

NEWS.md, _docs/website/index.html, defaults.ini, spouts/twitter/usertimeline.php, templates/item.phtml
The thumbnails, e.g. of the Youtube spout bloat the layout of the single
items while collapsed. This allows the user to hide the thumbnails via a
config option.
=> Add config option to hide the thumbnails

NEWS.md, composer.json, composer.lock, spouts/reddit/reddit2.php
Allow wider range of URLs in Reddit spout, including absolute URLs and searches.
=> Reddit spout fixes

templates/home.phtml
The logic is a leftover from before the login logic was moves client-side.
The f3 PHP templates seem to be happy with unknown properties but this would
cause some problems on some setups.
This may fix #1039 .
=> remove leftovers from before login was moved client-side

helpers/SimplePieFileGuzzle.php, spouts/rss/feed.php
SimplePie uses custom code for fetching resources from web but this is inconsistent and error-prone. To fix this, we will be overloading SimplePie’s `File` class with our own subclass using Guzzle.
Additionally, we will be no longer adding “Simplepie/X.Y.Z” string to the `User-Agent` header. Given that this is just an implementation detail, and that many websites actively block SimplePie.
=> Use Guzzle with SimplePIe

helpers/ContentLoader.php
I have a feed where SimplePie cannot parse the pubDate. The format looks like this: "<pubDate>ma, 08 okt 2018 10:09:29 +0000</pubDate>".
The result is a date for the item that is epoch (which is too old). Therefore the items will never show up in the reader as they are too old. By falling back to current time when the date cannot be parsed will make the items show up in selfoss.
=> Handle feeds with date that cannot be parsed

NEWS.md, controllers/Opml.php
To track the history of subscriptions, this adds a timestamp to the proposed export-filename. 
**selfoss-subscription.xml** becomes **selfoss-subscriptions-20190121160154.xml**
=> Add timestamp to export-filename

.travis.yml, composer.json, composer.lock, helpers/Image.php, helpers/SimplePieFileGuzzle.php, helpers/WebClient.php, spouts/facebook/page.php, spouts/github/commits.php, spouts/reddit/reddit2.php, spouts/rss/feed.php, spouts/rss/fulltextrss.php
Guzzle 5 handles URLs incorrectly. This required upgrade to Graby 2.0, which is still in development. This also bumps required PHP version to 5.6.
Tested:
Closes: #962, #1079
=> Port to Guzzle 6

NEWS.md, public/css/style.css, public/js/selfoss-events-entries.js
If long articles use columns, it forces the user to scroll up and down repeatedly.
This was originally introduced in a7f24906f9df3329a8d6fdd0088049e766b0f068 but later reverted for reasons unknown in 42e0ed4bfd3a95353fb3f458363eff0acc2ae691.
Let’s re-add the condition and also centre the body for nicer experience.
Closes: #1080, #629 
Example feed: https://dolphin-emu.org/blog/feeds/
cc @niol
=> Do not use columns for long articles

helpers/SimplePieFileGuzzle.php
In https://github.com/SSilence/selfoss/pull/1052, we introduced a class that allowed us to make SimplePie fetch feeds using Guzzle and then pass headers and content back to it. Unfortunately, SimplePie expects the headers to be lower-case and strings, whereas Guzzle returns original case and string arrays as mandated by PSR-7. This in turn broke autodiscovery.
Closes: https://github.com/SSilence/selfoss/issues/1130
=> SimplePieFileGuzzle: Fix autodiscovery

public/css/style.css, public/js/selfoss-events-entries.js, public/js/selfoss-shortcuts.js, public/js/selfoss-ui.js, public/lang/cs.json, public/lang/en.json, templates/home.phtml, templates/item.phtml, templates/tag.phtml
Closes: https://github.com/SSilence/selfoss/issues/1127, https://github.com/SSilence/selfoss/issues/1132, https://github.com/SSilence/selfoss/issues/1028
=> Various a11y fixes

controllers/Index.php, public/css/style.css, public/js/selfoss-base.js, public/js/selfoss-db.js, public/js/selfoss-events-entries.js, public/js/selfoss-events-entriestoolbar.js, public/js/selfoss-events-navigation.js, public/js/selfoss-events.js, public/js/selfoss-shortcuts.js, public/js/selfoss-ui.js, public/lang/en.json, public/package-lock.json, public/package.json, templates/hashpassword.phtml, templates/home.phtml, templates/item.phtml, templates/opml.phtml, templates/source-nav.phtml, templates/source.phtml, templates/tag.phtml
Lots of accessibility and usability fixes. #1133
=> a11y and usability fixes

NEWS.md, assets/js/selfoss-shortcuts.js, assets/js/selfoss-ui.js
Fixed aria-current for entry titles.
Previously the aria-current was getting applied to the whole entry.
=> A11y: fixed aria-current for entry titles

NEWS.md, README.md, composer.json, composer.lock, src/spouts/twitter/hometimeline.php, src/spouts/twitter/listtimeline.php, src/spouts/twitter/usertimeline.php
This concludes our effort to port selfoss to Guzzle.
https://www.sitepoint.com/using-guzzle-twitter-via-oauth/
=> spouts: Port Twitter spouts to Guzzle

_docs/website/index.html, _docs/website/style.css, assets/css/style.css, assets/js/icons.js, assets/js/selfoss-shares.js, assets/locale/en.json, assets/package-lock.json, assets/package.json
Fixes #1105 
- Still needs Translations.
- It might be worth making the pop-up at the top have absolute positioning so that it can be seen when the user scrolls down and a high z-index so that mobile users can see it when they have a item open.
Otherwise should be good to go. Tested on Firefox, Chrome both on Linux desktop and android.
=> Share button for copy

.gitignore, assets/css/style.css, assets/js/selfoss-ui.js, assets/locale/en.json
There were some typos in aria-labelled by.
Fixed them.
Previously they were written as aria-labeledby which I noticed that is wrong.
Also, made some improvements in the toolbar accessibility.
Excluded the assets/.cache directory from the VCS.
=> A11Y fixes for toolbar and some typo fixes for aria-labelledbyAccessibility

NEWS.md, assets/js/selfoss-base.js, docs/api-description.json, src/controllers/Items.php
PHP can only handle 1000 POST variables by default so marking will fail with more entries. Passing it as JSON is more reliable and even sends less data.
Fixes: https://github.com/SSilence/selfoss/issues/1037
=> Pass mass-marked entry ids as JSON

NEWS.md, _docs/website/index.html, src/helpers/FeedReader.php, src/helpers/Image.php, src/helpers/Misc.php, src/helpers/SimplePieFileGuzzle.php, src/helpers/WebClient.php, src/spouts/rss/feed.php, tests/Helpers/IconExtractorTest.php
Replaces https://github.com/SSilence/selfoss/pull/1124
=> Favicon improvements

NEWS.md, src/helpers/FeedReader.php, src/spouts/reddit/reddit2.php, src/spouts/rss/feed.php
Fixes: #1185 
Replaces: #1187 
SimplePie returns links escaped with htmlspecialchars but we might want to use the URL to fetch additional data so we need to unescape it first.
ContentLoader will escape it again before saving it to database.
=> spouts\rss: Provide unencoded link

assets/css/style.css, assets/js/icons.js, assets/js/selfoss-base.js, assets/js/selfoss-db.js, assets/js/selfoss-events-navigation.js, assets/js/selfoss-events-sources.js, assets/js/selfoss-sw-offline.js, assets/js/selfoss-ui.js, assets/js/templates.js, assets/locale/cs.json, assets/locale/en.json, assets/templates/nav-sources.js, assets/templates/nav-tags.js, index.php, src/controllers/Index.php, src/controllers/Items/Stats.php, src/controllers/Items/Sync.php, src/controllers/Sources.php, src/controllers/Sources/Write.php, src/controllers/Tags.php, src/templates/source-nav.phtml, src/templates/tag.phtml
Replaces #1064 
Instead of EJS, we now use JSX syntax so we can import the templates as a JavaScript modules and do not have to mess up with ejs loader.
This is a prerequisite for filtering entries by sources and tags offline.
=> Render navigation client-side

NEWS.md, src/common.php
F3 crashes when there were PHP startups error even though they might not affect the program (e.g. unable to load an extension). It also sets its own error_reporting value and uses the previous one as a signal to disable the initialization failure check.
Let's use that to avoid the crash and log the error ourselves.
Fixes: https://github.com/SSilence/selfoss/issues/1192
=> common: Do not crash on PHP startup error

assets/css/style.css, assets/js/lazy-image-loader.js, src/helpers/ViewHelper.php, src/templates/item.phtml, tests/Helpers/ImageLazifierTest.php
With lazy loading of images enabled, `img` tags did not have a `src` attribute, causing the browsers to render them as zero-height boxes. This made it impossible to determine the precise height of the article content, leading to articles sometimes being rendered in column view, even though they would not fit a single screen with images loaded.
In Firefox, it is possible to use broken non-image (e.g. about:blank page) and it will render a rectangle respecting the width and height ratio, there must be no alt attribute, though. And Chromium will not respect the aspect ratio either.
https://jsfiddle.net/jtojnar/yrdskx0n/5/
It is also possible to use a real image (e.g. 1×1 px dot) but then the `height: auto` in CSS causes the images to respect the size of the placeholder, not the specified …
=> helpers\ImageLazifier: set placeholder src

NEWS.md, src/spouts/twitter/Search.php, src/spouts/twitter/listtimeline.php, src/spouts/twitter/usertimeline.php
This will allow following hashtags. 
See the Twitter docs for info about query:
https://developer.twitter.com/en/docs/tweets/search/guides/standard-operators
Closes: #1211 
----
WIP since:
- It only fetches the latest page, which might not be enough when there are many tweets in a short span of time. We would need to handle pagination.
- NEWS entry and docs need to be updated.
- I do not really like adding more core spouts but am not sure how to fix this.
=> spouts\twitter: Add search

NEWS.md, src/common.php, src/helpers/ContentLoader.php, src/helpers/IconStore.php, src/helpers/Image.php, src/helpers/ImageHolder.php, src/helpers/ImageUtils.php, src/helpers/Storage/FileStorage.php, src/helpers/ThumbnailStore.php, src/spouts/reddit/reddit2.php, src/spouts/rss/feed.php, src/spouts/rss/images.php, src/spouts/spout.php, src/spouts/youtube/youtube.php, tests/Helpers/DetectSvgTest.php, tests/Helpers/IconExtractorTest.php
Avoid repeating requests and clean up the old spaghetti.
To allow distinguishing between an icon coming from the feed item and one from the feed itself, we added a new optional `getSourceIcon()` method. When the `getIcon()` method returns `null` for an item or the item icon cannot be fetched, the source icon will be used as a fallback.
Both `getSourceIcon()` and `getIcon()` can return `null` now when an icon is not available.
=> Refactor image fetching

NEWS.md, assets/.sassrc, assets/hashpassword.html, assets/index.html, assets/opml.html, assets/package-lock.json, assets/package.json, assets/styles/main.scss
Reset.css removes all styling including from elements like `<em>` or `<strong>`. Let’s reapply it in entry contents.
I had to switch to SASS to be able to use scoped @import.
The `unreset` library contains stuff we do not need (semantic layout elements) but it is still nicer than writing it from scratch.
Alternately, we could switch to something like normalize.css and remove stuff we do not want (e.g. list styling for `<ul>` in the sidebar) ourselves but that is more work and I am not sure how much sense it makes for us. https://css-tricks.com/reboot-resets-reasoning/
Fixes: #1220
=> client: re-add styles to content

NEWS.md, assets/locale/en.json, assets/styles/main.scss, defaults.ini, docs/content/docs/administration/options.md, src/controllers/About.php, src/templates/item.phtml
This addition displays an estimated reading time near the title of each article.
It allows me to estimate how long an article is before opening it.
It is just a small hack I made for my own use and I do not know if it actually is an useful feature for others... if it's not feel free to delete this PR.
=> Article reading time

.travis.yml, docs/content/docs/development/setting-up.md, docs/content/docs/development/using-nix.md, docs/sass/style.scss, flake.lock, flake.nix, utils/bintray.sh, utils/bump-version.js, utils/create-zipball.py, utils/nix/phps.nix
Previously we were installing
- PHP using Travis’s built-in mechanism that downloads distributions-specific tarballs (PHP 7.1 is not compatible with focal),
- Composer using itself,
- Python using pyenv (quite slow),
- Python libraries using pip,
- Node using nvm,
- jq using apt,
- PHP dependencies using Composer,
- client-side dependencies using npm.
Switching to Nix will allow us to get rid of all except the last two methods and achieve fully reproducible environment across both CI and developers’ machines.
The travis config is based on https://github.com/cachix/travis-ci-example.
Also allows us to switch distribution to focal.
=> ci: Use Nix for obtaining dependencies

NEWS.md, assets/js/helpers/uri.js, assets/js/templates/SearchList.jsx, assets/styles/main.scss, src/common.php, src/daos/StatementsInterface.php, src/daos/mysql/Items.php, src/daos/mysql/Statements.php, src/daos/pgsql/Statements.php, src/daos/sqlite/Statements.php, src/helpers/ViewHelper.php
When user searches a term starting and ending with a forward slash, the items will be matched against the regular expression between the slashes.
The syntax of the regular expressions is database-engine specific:
* MySQL uses POSIX extended https://dev.mysql.com/doc/refman/5.7/en/regexp.html
* PostgreSQL uses POSIX extended with some extensions https://www.sqlite.org/lang_expr.html#the_like_glob_regexp_and_match_operators
* SQLite uses PHP’s PCRE https://www.postgresql.org/docs/12/functions-matching.html#FUNCTIONS-POSIX-REGEXP, https://www.php.net/manual/en/book.pcre.php
------
~~The filtering works but the interface is still incomplete. In particular, the matches will not be highlighted in the articles, and the search regex will be shown split on spaces.~~ Fixed.
=> Support search using regex

NEWS.md, assets/js/templates/ColorChooser.jsx, assets/js/templates/NavTags.jsx
For some reason, the initial value is no longer taken from the background colour (if it ever was). Let’s pass the colour to spectrum to have it selected instead of the terrible hardcoded colour.
The downside is that changing a colour (and closing the popover) will cause the spectrum instance to be torn down and re-created. But the other simple alternative of caching the initial colour using `React.useState` would prevent updating the selected value from tag synchronization API response.
=> client: make spectrum respect changed the current color

assets/.eslintrc.json, assets/js/helpers/ajax.js, assets/js/requests/items.js, assets/js/requests/sources.js, assets/js/selfoss-base.js, assets/js/selfoss-db-offline.js, assets/js/selfoss-db-online.js, assets/js/shortcuts.js, assets/js/templates/EntriesPage.jsx, assets/js/templates/Item.jsx, assets/js/templates/NavTags.jsx, assets/js/templates/SourcesPage.jsx, assets/package-lock.json, assets/package.json
This was always an issue but the React port made it extra obvious. Let’s have the components maintain their own `AbortController`s as suggested by <https://dev.to/viclafouch/cancel-properly-http-requests-in-react-hooks-and-avoid-memory-leaks-pd7>. It is cleaner too.
=> client: Cancel previous requests more reliably

NEWS.md, docs/content/docs/administration/options.md, src/common.php, src/helpers/Configuration.php
Unlike PostgreSQL, MySQL’s DSN needs a separate option for UNIX sockets. It also cannot handle ports with socket.
This will be useful for running tests with internal MySQL instance.
=> common: Support MySQL through socket

assets/js/templates/NavFilters.jsx
It makes more sense to throw away the selected article as the user clearly finished reading when they want to change the category.
Addresses @xvasek’s first point in https://selfoss.aditu.de/forum/index.php?id=1447
=> client: Clear id when changing filter

assets/js/templates/Item.jsx, assets/js/templates/LoginForm.jsx, cliupdate.php, composer.json, composer.lock, index.php, src/common.php, src/controllers/Authentication.php, src/controllers/Index.php, src/controllers/Items.php, src/controllers/Rss.php, src/controllers/Sources.php, src/controllers/Sources/Update.php, src/controllers/Sources/Write.php, src/controllers/Tags.php, src/daos/ItemOptions.php, src/daos/Items.php, src/daos/ItemsInterface.php, src/daos/mysql/Items.php, src/helpers/Authentication.php, src/helpers/ContentLoader.php, src/helpers/View.php
- Do not use AJAX detection from F3
- Do not do localization on the server
- daos\items: Use value object for query options
- Do not use F3 for base URI detection
- Do not use F3 for HTTP errors
- **Switch to bramus\router for routing**
We still need to get rid of Database and error logging. Unfortunately “fat-free” will destroy error handling if even a sliver remains so Database will have to go first.
=> Reduce fatfree usage some more

NEWS.md, assets/js/templates/Source.jsx, assets/js/templates/SourceParam.jsx, assets/js/templates/SourcesPage.jsx, index.php
Visiting `/manage/sources/add?url=foo` will load the settings page, open the “new source” form and pre-fill the URL specified in the query string parameter. For now, only URL is customizable.
Fixes: https://github.com/fossar/selfoss/issues/254
=> client: Add route for adding RSS sources

src/helpers/ItemsIterator.php, src/spouts/facebook/page.php, src/spouts/github/commits.php, src/spouts/reddit/reddit2.php, src/spouts/rss/enclosures.php, src/spouts/rss/feed.php, src/spouts/rss/images.php, src/spouts/twitter/usertimeline.php, src/spouts/youtube/youtube.php
This will make it easier to implement spouts that do not fetch all items at once.
Also fix return values of the ItemsIterator:
- Iterator::next() should not return anything.
- null should be returned when Iterator is invalid.
=> spouts: Use Iterator for items internally

NEWS.md, assets/js/templates/Source.jsx, assets/locale/cs.json, assets/locale/en.json, assets/package-lock.json, assets/package.json, assets/styles/main.scss, assets/styles/popup-menu.scss
Partly fixes: https://github.com/fossar/selfoss/issues/1324
=> client: Add a link from settings page to individual sources

NEWS.md, README.md, assets/js/helpers/color.js, assets/js/icons.js, assets/js/index.js, assets/js/templates/ColorChooser.jsx, assets/js/templates/NavTags.jsx, assets/locale/cs.json, assets/locale/en.json, assets/package-lock.json, assets/package.json, assets/styles/color-chooser.scss, assets/styles/main.scss, assets/styles/mixins/visually-hidden.scss
It is unmaintained, depends on jQuery and Parcel no longer wants to parse its CSS (asterisk hack before display property for IE 7 support).It is unmaintained, depends on jQuery and Parcel no longer wants to parse its CSS (asterisk hack before display property for IE 7 support).
Fixes: https://github.com/fossar/selfoss/issues/1268
<del>Unfortunately, this probably will not work due to the sidebar containing the menu button being `position: fixed` and `overflow: hidden`.
We might need to use something like [popper](https://popper.js.org/react-popper/v2/) to get reasonable placement of the popup.</del>
Switched to [Floating UI](https://floating-ui.com/) (Popper successor) and it works okay.
It would be nice to have arrow pointing to the tag being changed but I did not manage to align it …
=> Do not use spectrum for colorpicker

NEWS.md, assets/js/templates/EntriesPage.jsx, assets/js/templates/Source.jsx, assets/js/templates/SourcesPage.jsx, assets/locale/cs.json, assets/locale/en.json, assets/styles/main.scss
Fixes: https://github.com/fossar/selfoss/issues/1324
=> client: Add link from source entries to settings

NEWS.md, src/helpers/ContentLoader.php, src/spouts/facebook/page.php, src/spouts/github/commits.php, src/spouts/reddit/reddit2.php, src/spouts/rss/feed.php, src/spouts/spout.php, src/spouts/twitter/usertimeline.php
Reverts https://github.com/fossar/selfoss/pull/1057.
=> spout: Return DateTimeInterface from getDate

NEWS.md, assets/js/shortcuts.js, docs/content/docs/administration/options.md, src/controllers/About.php, src/helpers/Configuration.php
Fixes: https://github.com/fossar/selfoss/issues/55
=> client: Support opening articles in background tab (Firefox only)

NEWS.md, assets/js/selfoss-base.js, assets/js/templates/Item.jsx, docs/content/docs/administration/options.md, src/controllers/About.php, src/helpers/Configuration.php
Initially implemented in https://github.com/fossar/selfoss/issues/104, these were mostly meant to strip the `Referer` header. But we have long been specifying `rel="noreferer"` on links, which achieved the same effect without going through a questionable third-party website that usually messed up the viewed web page.
For better privacy, web browser extensions like NoScript or uBlock Origin and Tor or a VPN provider are probably much better anyway.
Closes: https://github.com/fossar/selfoss/issues/612
=> Remove anonymizer support

NEWS.md, assets/js/errors.js, assets/js/helpers/ajax.js, assets/js/helpers/i18n.js, assets/js/requests/common.js, assets/js/requests/sources.js, assets/js/selfoss-base.js, assets/js/templates/LoginForm.jsx, assets/locale/cs.json, assets/locale/en.json, docs/api-description.json, index.php, src/constants.php, src/controllers/Sources/Update.php
- Emphasize Cookie auth in docs
- Replace `GET /logout` with `DELETE /api/session/current`
- Deprecate `POST /source/delete/:id`
- Make `POST /source/update` and `POST /source/:id/update` return 403 on authorization failure (cc @davidoskky for #1357)
cc @aminecmi
=> Update API docs & deprecate some older ones

NEWS.md, assets/js/opml.js, src/controllers/Opml/Import.php
- opml/import: Use `text` attribute for tag names
- opml/import: Prefer `title` attribute for source names
- client: Escape error messages in OPML import
- opml/import: Allow importing files even if browser reports wrong MIME type
=> Improve OPML conformance

NEWS.md, assets/js/requests/sources.js, assets/js/templates/Item.jsx, assets/js/templates/Source.jsx, docs/api-description.json, docs/content/docs/administration/requirements.md, docs/content/docs/customization/api.md, flake.nix, src/constants.php, src/controllers/Opml/Import.php, src/daos/mysql/Database.php, src/daos/pgsql/Database.php, src/daos/sqlite/Database.php, src/helpers/ContentLoader.php, src/helpers/FeedReader.php, src/spouts/github/commits.php, src/spouts/rss/feed.php, src/spouts/twitter/usertimeline.php
=> Fix some 2.19 regressions and improve twitter and github spouts

NEWS.md, src/spouts/rss/feed.php
When SimplePie is unable to parse an item update date, it will return `false`, breaking the promise in PHPDoc. Since we do not expect it, we would try to treat the non-null value as a an int and try to create a date object from it, which lead to the affected sources failing to update with the following error:
Exception: DateTimeImmutable::__construct(): Failed to parse time string (@) at position 0 (@)
I have created an upstream PR:
https://github.com/simplepie/simplepie/pull/753
But until that is available, let’s work around the issue by also guarding against `false`.
Closes: https://github.com/fossar/selfoss/issues/1384
=> spouts\rss\feed: Work around SimplePie returning incorrect date value

.github/workflows/main.yaml, phpstan.neon
The “Parameter #2 $algo of function password_hash expects int, string given.” error only occurs on PHP ≥ 7.4 so running PHPStan with PHP 7.2 would fail with “Error: Ignored error pattern (Parameter #2 \$algo of function password_hash expects int, string given\.) was not matched in reported errors.”
=> ci: Fix PHPStan

NEWS.md, docs/api-description.json, src/daos/mysql/Items.php, src/helpers/ContentLoader.php, src/helpers/HtmlString.php, src/helpers/ImageUtils.php, src/spouts/Item.php, src/spouts/facebook/page.php, src/spouts/github/commits.php, src/spouts/reddit/reddit2.php, src/spouts/rss/enclosures.php, src/spouts/rss/feed.php, src/spouts/rss/fulltextrss.php, src/spouts/twitter/usertimeline.php, tests/Spouts/YouTubeTest.php
The database also contains other escaped values:
- https://github.com/fossar/selfoss/blob/ac61872689c24352ed912a231974376b15d41657/src/helpers/ViewHelper.php#L144
- https://github.com/fossar/selfoss/blob/0920dcbd1fe18a5369f7fe49dea8e7f0e2bfbeeb/src/controllers/Sources/Write.php#L78
- https://github.com/fossar/selfoss/blob/0920dcbd1fe18a5369f7fe49dea8e7f0e2bfbeeb/src/controllers/Sources/Write.php#L82
Similarly the view layer:
- https://github.com/fossar/selfoss/blob/ac61872689c24352ed912a231974376b15d41657/src/helpers/ViewHelper.php#L144
So I decided to first systematize the data model by using explicit object for HTML string.
Now we just need to remove the escaping everywhere else (will be a BC break).
=> Use HtmlString to distinguish between HTML and plain text strings

assets/js/icons.js, assets/js/sharers.jsx, assets/locale/de.json, assets/locale/en.json, docs/content/docs/administration/options.md, src/controllers/About.php, src/helpers/Configuration.php
Given the recent influx of users on Mastodon, I thought it would be nice to add a "Share on Mastodon" button.
As users are on different mastodon instances with different URLs, we need a new Configuration option to store the URL of the mastodon instance.
I added the option description to the documentation and the English and German translation for the label.
The link leads to a page on which the user can edit and publish the mastodon post, pre-filled with the entries title in quotes and its URL.
What do you think?
=> Add 'Share on Mastodon' functionality

NEWS.md, docs/content/docs/usage/filters.md, src/controllers/Sources/Write.php, src/helpers/ContentLoader.php, src/helpers/Filters/AcceptingFilter.php, src/helpers/Filters/DisjunctionFilter.php, src/helpers/Filters/Filter.php, src/helpers/Filters/FilterFactory.php, src/helpers/Filters/FilterSyntaxError.php, src/helpers/Filters/MapFilter.php, src/helpers/Filters/NegationFilter.php, src/helpers/Filters/RegexFilter.php, tests/Helpers/FilterTest.php
The filter expression can take one of the following forms:
1. An *atomic filter*: a Perl-compatible regular expression, as [accepted by PHP](https://www.php.net/manual/en/reference.pcre.pattern.syntax.php), between forward slashes (`/`). For example, `/reg(ular expression|ex)/` will keep only items whose title or content matches the regular expression between the slashes (i.e. contain the phrase “regular expression” or “regex”). Learn more about regular expressions on <https://www.regular-expressions.info/>.
2. A *field-specific filter*: an *atomic filter* preceded by one of the field names below and a colon:
- `title:/regex/` will keep only items whose title matches the regular expression between the slashes.
- `content:/regex/` will keep only items whose content matches the regular …
=> Improve filter support

NEWS.md, docs/content/docs/usage/filters.md, src/helpers/Filters/FilterFactory.php, tests/Helpers/FilterTest.php
Follow up to #1423.
This is useful for e.g. removing articles that have categories in the URL instead of in the feed, like BBC has.
One can, for example, ignore sport news with `!url:/^https:\/\/www\.bbc\.co\.uk\/sport\//` as the filter.
=> Support url filters

NEWS.md, assets/js/requests/sources.js, cliupdate.php, docs/api-description.json, src/constants.php, src/controllers/Sources/Update.php, src/daos/Sources.php, src/daos/SourcesInterface.php, src/daos/mysql/Sources.php, src/helpers/ContentLoader.php, src/helpers/UpdateVisitor.php
This will reduce the chance that the web server will time out due to no response being sent. In the future, we will be able to use the data for displaying a progress bar in the client.
Even though the `GET /update` endpoint is not actually part of the public API, we increase the API version to 6.0.1 → 6.1.0, and only use the new output when `Accept: text/event-stream` header is sent with the request, in order to preserve backwards compatibility.
This is using Server-sent events-style response with three event types:
- `started`, with `count` data field containing the number of sources that will be updated
- `sourceUpdated`, with `finishedCount` data field containing the number of sources that will have been updated so far
- `finished` …
=> Update: Support sending update status after each source

NEWS.md, assets/js/helpers/authorizations.js, assets/js/templates/App.jsx
With `public=0`, when user logs in, sometimes the logged in state would not reflect to the `CheckAuthorization` component, so the entries page wrapped in `CheckAuthorization` would redirect user back to log-in page.
=> client: Fix log-in loop

NEWS.md, assets/js/requests/sources.js, src/controllers/Sources/Update.php
Follow-up to 9741e39d1fa4070d4d42e774c8c088da055eaa7b.
Various layers in the network stack including php-fpm, Apache’s `mod_proxy_fcgi` and Nginx’s `ngx_http_fastcgi_module` will buffer responses.
Since the individual events are short compared to buffer sizes, it may happen that PHP keeps holding onto the output, waiting for the response buffer to fill up, and, in the meanwhile, nginx will time out waiting for the contents.
Let’s prevent that by ending all output buffering we can on PHP side.
(There would be ¿up to two? levels: one for `output_buffering`, one for `zlib.output_compression`.)
Web server buffering is not that critical (unless there is another layer like a proxy) but it is useful to disable it as well so that progress updates are reflected live. We will do that for nginx, …
=> Update: Ensure that progress reports are sent ASAP

client/js/templates/App.jsx, client/js/templates/EntriesPage.jsx
Some state action dispatchers in class components would refer to `this.state` property when given a function as the action argument. Since React 18 automatically batches state updates, calling such broken dispatcher after another dispatch in the same render might discard the changes performed by the earlier dispatcher because `this.state` would contain the state before the render started.
Let’s pass a function to `this.setState` and use the state argument provided by the dispatch to always get the freshest state.
Fixes: https://github.com/fossar/selfoss/issues/1454
=> client: Fix state handling

NEWS.md, docs/api-description.json, src/constants.php, src/helpers/Configuration.php
The frontend compared the Wallabag version with a number using strict comparison since 16f1cd6a52ee6dffac61d82a7fdd368c8b4ecd68.
But when we switched to a custom configuration container in 1f194f8ca5edcc8f353f1d0d131ccb2ccd1ad087 (part to 2.19),
we accidentally made the version a string breaking sharing to Wallabag.
Bumping the API version since changes the type of field in `/api/about` endpoint, even though the fields are explicitly not part of the API promise.
=> config: Fix Wallabag version type

NEWS.md, src/daos/Items.php, src/daos/ItemsInterface.php, src/daos/mysql/Items.php, src/daos/sqlite/Database.php
[SQLite](https://www.sqlite.org/quirks.html#dblquote), [MySQL](https://dev.mysql.com/doc/refman/5.7/en/string-literals.html) but not [PostgreSQL](https://dev.mysql.com/doc/refman/5.7/en/string-literals.html) support using double quotes for string literals in some places. This is generally considered a bad practice and SQLite [recommends disabling the feature](https://www.sqlite.org/compile.html#recommended_compile_time_options), which FreeBSD does, resulting in an error on startup:
no such column: table
Let’s fix the syntax to use ANSI SQL quoting style.
=> daos: Avoid double quotes for string literals

CONTRIBUTING.md, README.md
Having read Hintjens’s [Social Architecture](https://hintjens.gitbooks.io/social-architecture/content/) book, I want to try to build a community around selfoss, so that I am not the sole developer forever.
Until then, I need to document the current state so that people do not expect more than I have the capacity to provide.
I have also added a [README to my GitHub profile](https://github.com/jtojnar/jtojnar) that describes my work style and availability.
=> docs: clarify project status

.github/workflows/main.yaml, README.md
This is still broken:  https://github.com/cloudsmith-io/action/issues/60
=> README: Remove the latest build link

composer.json, composer.lock, phpstan.neon, src/controllers/Index.php, src/controllers/Items.php, src/controllers/Items/Sync.php, src/controllers/Rss.php, src/daos/ItemOptions.php, src/daos/Sources.php, src/daos/mysql/Items.php, src/helpers/FeedReader.php, src/helpers/ImageUtils.php, src/helpers/WebClient.php, src/spouts/Item.php, src/spouts/twitter/TwitterV1ApiClient.php, src/spouts/twitter/TwitterV1ApiClientFactory.php, tests/Spouts/TwitterTest.php
https://phpstan.org/blog/phpstan-2-0-released-level-10-elephpants
=> composer: Update PHPStan to 2.0

NEWS.md, src/common.php, src/controllers/About.php, src/controllers/Authentication.php, src/controllers/Helpers/HashPassword.php, src/controllers/Index.php, src/controllers/Items.php, src/controllers/Items/Stats.php, src/controllers/Items/Sync.php, src/controllers/Opml/Export.php, src/controllers/Opml/Import.php, src/controllers/Rss.php, src/controllers/Sources.php, src/controllers/Sources/Write.php, src/controllers/Tags.php, src/helpers/Authentication.php, src/helpers/Authentication/AuthenticationFactory.php, src/helpers/Authentication/AuthenticationService.php, src/helpers/Authentication/Services/RequestOrSession.php, src/helpers/Authentication/Services/Trust.php, src/helpers/Session.php, src/helpers/View.php, tests/integration/helpers/selfoss_api.py, tests/integration/run.py
This is a from-scratch rewrite, moving a bit closer to Single Responsibility Principle.
We split handling of credentials-in-config and always-open authentication systems.
In the future, we will be able implement more methods this way.
This was motivated by session code being called in constructor,
which would break in CLI with Tracy strict mode.
For now, we are just porting the Authentication helper and controller.
Additionally:
- Session verification now also checks if the credentials in the config did not change.
- Requests from loopback IP address now give full access to all operations, not just update.
- IPv6 loopback address is recognized as well.
- Requests forwarded by proxies are filtered out since local reverse proxies might come from loopback as well.
One thing I do not like …
=> Rework Authentication into separate services

client/js/helpers/hooks.js, client/js/helpers/uri.js, client/js/selfoss-base.js, client/js/templates/App.jsx, client/js/templates/EntriesPage.jsx, client/js/templates/HashPassword.jsx, client/js/templates/Item.jsx, client/js/templates/LoginForm.jsx, client/js/templates/NavFilters.jsx, client/js/templates/NavSearch.jsx, client/js/templates/NavSources.jsx, client/js/templates/NavTags.jsx, client/js/templates/NavToolBar.jsx, client/js/templates/OpmlImport.jsx, client/js/templates/SearchList.jsx, client/js/templates/Source.jsx, client/js/templates/SourcesPage.jsx, client/package-lock.json, client/package.json
~~Unfortunately, regular expressions in routes are no longer supported so URLs like `/newest/source-2/143` or `/unread/tag-news/259` will no longer work. We will need to switch them to something like `/sources/2?filter=newest#143` and that will collide with the server API, so it will need to be moved to `/api/` subdirectory.~~ I managed to work around https://github.com/remix-run/react-router/issues/8254 with intermediary `EntriesFilter` component with a custom validation logic.
Though I do not really like the direction of the library towards frameworkization.
=> Update to react-router 7

client/js/helpers/i18n.js, client/js/selfoss-db-offline.js, client/js/selfoss-db.js, client/js/templates/App.jsx, client/js/templates/EntriesPage.jsx, client/js/templates/HashPassword.jsx, client/js/templates/Item.jsx, client/js/templates/LoginForm.jsx, client/js/templates/NavSources.jsx, client/js/templates/NavTags.jsx, client/js/templates/Navigation.jsx, client/js/templates/OpmlImport.jsx, client/js/templates/Source.jsx, client/js/templates/SourceParam.jsx, client/js/templates/SourcesPage.jsx, client/js/templates/Spinner.jsx, src/controllers/Index.php, src/helpers/ViewHelper.php
=> Various mostly client cleanups

client/js/templates/EntriesPage.jsx, client/js/templates/SourcesPage.jsx
Regressions from https://github.com/fossar/selfoss/commit/88deedea994efe4cdf97207deed9a292057da80a
Fixes: https://github.com/fossar/selfoss/issues/1513
=> client: Fix navigation regressions

src/helpers/Search.php, tests/integration/helpers/selfoss_api.py, tests/integration/run.py
On PHP 8.4 search would fail with the following:
str_getcsv(): the $escape parameter must be provided as its default value will change
As per <https://www.php.net/manual/en/function.str-getcsv.php>, relying on the default value of escape is now deprecated.
Also add a test to ensure search continues to work.
Fixes: https://github.com/fossar/selfoss/issues/1516
=> search: Fix on PHP 8.4

client/js/templates/EntriesPage.jsx
Fixes 'TypeError: can't access property starred, r is undefined' introduced in 00cf3d6 (#1512).
=> Fix TypeError when refreshing entry statuses

composer.lock
Changelogs summary:
- friendsofphp/php-cs-fixer updated from v3.88.1 to v3.88.2 patch
See changes: https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/compare/v3.88.1...v3.88.2
Release notes: https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/releases/tag/v3.88.2
- j0k3r/graby-site-config updated from 1.0.203 to 1.0.204 patch
See changes: https://github.com/j0k3r/graby-site-config/compare/1.0.203...1.0.204
Release notes: https://github.com/j0k3r/graby-site-config/releases/tag/1.0.204
- phpstan/phpstan updated from 2.1.29 to 2.1.30 patch
- symfony/phpunit-bridge updated from v7.3.3 to v7.3.4 patch
See changes: https://github.com/symfony/phpunit-bridge/compare/v7.3.3...v7.3.4
Release notes: https://github.com/symfony/phpunit-bridge/releases/tag/v7.3.4
Fixes: #1529
=> composer: Update dependencies
